# Site wide configuration

title:            Simon Prégent
locale:           en_CA
url:              //awarewolf.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Simon Prégent
  avatar: bio-photo.jpg
  bio: "Junior full-stack ruby on rails web developer, BI professional and all around data wonk."
  email: info@awarewolf.ca
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-66830022-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: awarewolf
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: simonpregent
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
